version: "3.8"
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    container_name: nest
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    command: npm run start:dev
    ports:
      - "3030:3030"
    labels:
      - "traefik.http.routers.api.rule=Host(`nest.localhost`)"
    depends_on:
      - db
  db:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
  traefik:
    image: traefik:v2.9
    container_name: traefik
    network_mode: "host"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  dbdata: